from pathlib import Path
p=Path('/mnt/data/work9/index.html')
s=p.read_text(encoding='utf-8')
start=s.index('<section class="section" data-cultural-section="handicrafts"')
end=s.index('<section class="section" data-cultural-section="clothing"', start)
section=r'''<section class="section craft-section" data-cultural-section="handicrafts" data-master-section="true" id="handicrafts">
<h2 data-ar="الحرف والصناعات اليدوية الكردية" data-en="Kurdish Handicrafts &amp; Traditional Crafts" data-fa="صنایع دستی و هنرهای سنتی کردی" data-ku="دەستکاری و هونەرە پیشەییە کوردییەکان" data-tr="Kürt El Sanatları ve Geleneksel Zanaatlar">دەستکاری و هونەرە پیشەییە کوردییەکان</h2>
<div class="craft-hero-box">
  <div>
    <span class="craft-kicker">KURDESTAN • CULTURAL ARCHIVE • 09</span>
    <h3 data-ku="دەستکاریی کوردی؛ هونەر، ژیان و یادەوەری" data-en="Kurdish handicrafts: art, livelihood and memory" data-fa="صنایع دستی کردی؛ هنر، معیشت و حافظه فرهنگی" data-tr="Kürt el sanatları: sanat, geçim ve kültürel hafıza" data-ar="الحرف الكردية: فن ومعيشة وذاكرة ثقافية">دەستکاریی کوردی؛ هونەر، ژیان و یادەوەری</h3>
    <p data-ku="ئەم بەشە دەستکارییەکان و پیشە کۆنەکانی ناوچە کوردنشینەکانی ڕۆژهەڵات، باکوور، باشوور و ڕۆژئاوا بە شێوەی ناوچەیی دەخاتەڕوو. جیاوازیی نێوان بەرهەمی شارستانی، گوندی، هۆزی و بازاڕی پارێزراوە و هیچ بەرهەمێک بە بێ بەڵگە بە ناوی کوردیی تایبەت نادرێت." data-en="This section documents craft traditions found among Kurdish communities across Rojhelat, Bakur, Başûr and Rojava. It distinguishes urban, village, tribal and market traditions and avoids presenting a shared regional craft as exclusively Kurdish without evidence." data-fa="این بخش سنت‌های صنایع دستی در میان جوامع کرد در روژهلات، باکوور، باشور و روژاوا را به‌صورت منطقه‌ای مستند می‌کند. میان سنت‌های شهری، روستایی، عشایری و بازاری تفکیک شده و هیچ هنر مشترک منطقه‌ای بدون مدرک «منحصراً کردی» معرفی نمی‌شود." data-tr="Bu bölüm Rojhelat, Bakur, Başûr ve Rojava'daki Kürt topluluklarında görülen el sanatlarını bölgesel olarak belgeler. Şehir, köy, aşiret ve pazar gelenekleri ayrılır; ortak bölgesel bir zanaat kanıt olmadan yalnızca Kürtlere ait gösterilmez." data-ar="يوثق هذا القسم الحرف لدى المجتمعات الكردية في روجهلات وباكور وباشور وروج آفا بصورة إقليمية، مع التمييز بين تقاليد المدن والقرى والعشائر والأسواق، وتجنب وصف الحرف المشتركة إقليمياً بأنها كردية حصراً دون دليل.">ئەم بەشە دەستکارییەکان و پیشە کۆنەکانی ناوچە کوردنشینەکان بە شێوەی ناوچەیی و بە هەستی زانستی دەخاتەڕوو.</p>
  </div>
  <div class="craft-stat-row"><span><b>12+</b><small data-ku="جۆری سەرەکی" data-en="core craft families" data-fa="خانواده اصلی هنرها" data-tr="ana zanaat ailesi" data-ar="عائلات حرفية أساسية">جۆری سەرەکی</small></span><span><b>4</b><small data-ku="ناوچەی کوردستان" data-en="regional zones" data-fa="منطقه اصلی" data-tr="bölge" data-ar="مناطق إقليمية">ناوچەی کوردستان</small></span><span><b>∞</b><small data-ku="شێواز و نەخش" data-en="motifs &amp; variations" data-fa="نقش و تنوع" data-tr="motif ve varyasyon" data-ar="زخارف وتنوعات">شێواز و نەخش</small></span></div>
</div>

<div class="craft-method-box">
  <h3 data-ku="چۆنیەتی خوێندنەوەی ئەم بەشە" data-en="How to read this craft archive" data-fa="روش مطالعه این آرشیو" data-tr="Bu arşiv nasıl okunmalı?" data-ar="كيفية قراءة هذا الأرشيف">چۆنیەتی خوێندنەوەی ئەم بەشە</h3>
  <div class="craft-method-grid">
    <div><b>01</b><span data-ku="مادەی سەرەکی: پشم، پەمۆ، پەڕە، ئاوەڵ، دار، چەرم، گڵ و کانزا." data-en="Material: wool, cotton, silk, wood, leather, clay and metals." data-fa="مواد: پشم، پنبه، ابریشم، چوب، چرم، گل و فلزات." data-tr="Malzeme: yün, pamuk, ipek, ahşap, deri, kil ve metaller." data-ar="المادة: الصوف والقطن والحرير والخشب والجلد والطين والمعادن.">مادەی سەرەکی</span></div>
    <div><b>02</b><span data-ku="تکنیک: بافتن، گره‌دان، دوورین، سوزن‌کاری، چەقۆڵ، کۆڵان، خەراطی و پێکهێنان." data-en="Technique: weaving, knotting, embroidery, carving, turning, forging and assembly." data-fa="فناوری: بافت، گره‌زنی، سوزن‌دوزی، کنده‌کاری، خراطی، آهنگری و مونتاژ." data-tr="Teknik: dokuma, düğümleme, nakış, oyma, tornacılık, dövme ve birleştirme." data-ar="التقنية: النسيج والعقد والتطريز والنحت والخراطة والحدادة والتركيب.">تکنیک</span></div>
    <div><b>03</b><span data-ku="کارکرد: ماڵ، جلوبەرگ، کەلوپەل، ئاڕاستە، ئاڵەت و بەرهەمی بازاڕ." data-en="Function: household, clothing, utility, decoration, instruments and market goods." data-fa="کارکرد: خانه، پوشاک، ابزار، تزئین، ساز و محصولات بازار." data-tr="İşlev: ev, giyim, kullanım, süsleme, çalgı ve pazar ürünleri." data-ar="الوظيفة: منزلية وملابس وأدوات وزينة وآلات موسيقية ومنتجات سوقية.">کارکرد</span></div>
    <div><b>04</b><span data-ku="سەرچاوەی وێنە: زۆربەی وێنەکان لە Wikimedia Commons ـە و مۆڵەتی بەکارهێنانیان لە ژێر هەر وێنەیەک دیارە." data-en="Image sources: most photographs come from Wikimedia Commons with license/author information shown under each image." data-fa="منبع تصاویر: بیشتر تصاویر از Wikimedia Commons با ذکر مجوز و پدیدآورنده استفاده شده‌اند." data-tr="Görsel kaynakları: çoğu fotoğraf Wikimedia Commons'tan, lisans ve yazar bilgisiyle alınmıştır." data-ar="مصادر الصور: معظم الصور من Wikimedia Commons مع ذكر الترخيص والمؤلف أسفل كل صورة.">سەرچاوەی وێنە</span></div>
  </div>
</div>

<div class="craft-region-summary">
  <h3 data-ku="خشتەی ناوچەیی: چوار پارچە" data-en="Regional map: four parts" data-fa="نقشه منطقه‌ای: چهار بخش" data-tr="Bölgesel harita: dört parça" data-ar="الخريطة الإقليمية: أربعة أجزاء">خشتەی ناوچەیی: چوار پارچە</h3>
  <div class="craft-region-grid">
    <div class="craft-region"><strong>ڕۆژهەڵات</strong><span data-ku="سنە، بیجار، کرماشان، پاوە، هەورامان، موکریان و خۆراسانی کوردی: قاڵی و گلیم، جاجم، کڵاش، دارکاری، چەرم و فلزکاری." data-en="Sanandaj, Bijar, Kermanshah, Paveh, Hawraman, Mukriyan and Kurdish Khorasan: carpets, kilims, jajim, klash, wood, leather and metalwork." data-fa="سنندج، بیجار، کرمانشاه، پاوه، هورامان، مکریان و خراسان کرد: قالی، گلیم، جاجیم، کلاش، چوب، چرم و فلزکاری." data-tr="Sanandaj, Bijar, Kermanshah, Paveh, Hewraman, Mukriyan ve Kürt Horasanı: halı, kilim, jajim, klash, ahşap, deri ve metal işleri." data-ar="سنندج وبيجار وكرمانشاه وباوه وهورامان ومكريان وخراسان الكردية: السجاد والكليم والجاجيم والكلاش والخشب والجلد والمشغولات المعدنية.">قاڵی، گلیم، جاجم، کڵاش، دارکاری و فلزکاری</span></div>
    <div class="craft-region"><strong>باکوور</strong><span data-ku="هەکاری، دیاربەکر، وان، ماردین، باتمان و ناوچەکانی ڕۆژهەڵاتی ئەناتۆڵیا: بافت، قاڵی، گلیم، چەرم، زیوەر و پیشە بازاڕییەکان." data-en="Hakkâri, Diyarbakır, Van, Mardin, Batman and eastern Anatolia: weaving, rugs, kilims, leather, jewelry and bazaar crafts." data-fa="هکاری، دیاربکر، وان، ماردین، باتمان و شرق آناتولی: بافت، قالی، گلیم، چرم، زیور و صنایع بازار." data-tr="Hakkâri, Diyarbakır, Van, Mardin, Batman ve Doğu Anadolu: dokuma, halı, kilim, deri, takı ve çarşı zanaatları." data-ar="هكاري ودياربكر ووان وماردين وباتمان وشرق الأناضول: النسيج والسجاد والكليم والجلد والمجوهرات وحرف الأسواق.">بافت، قاڵی، گلیم، زیوەر و چەرم</span></div>
    <div class="craft-region"><strong>باشوور</strong><span data-ku="هەولێر، سلێمانی، دهۆک، زاخۆ، بارزان و هەورامان: قاڵی، زیوەر، مسگری، بافتی جل و بەرهەمە ماڵییەکان." data-en="Erbil, Sulaymaniyah, Duhok, Zakho, Barzan and Hawraman: rugs, jewelry, copperwork, textiles and household crafts." data-fa="اربیل، سلیمانیه، دهوک، زاخو، بارزان و هورامان: قالی، زیور، مسگری، منسوجات و صنایع خانگی." data-tr="Erbil, Süleymaniye, Duhok, Zakho, Barzan ve Hewraman: halı, takı, bakırcılık, tekstil ve ev zanaatları." data-ar="أربيل والسليمانية ودهوك وزاخو وبارزان وهورامان: السجاد والمجوهرات والنحاس والمنسوجات والحرف المنزلية.">قاڵی، زیوەر، مسگری و بافت</span></div>
    <div class="craft-region"><strong>ڕۆژئاوا</strong><span data-ku="ناوچە کوردنشینەکانی سوریا: بافت و دەستکاریی پەیوەندیدار بە ژیانی گوندی و بازاڕی؛ بە هەستی زانستی جیاوازی ناوچەیی دەپارێزرێت." data-en="Kurdish-populated areas of Syria: weaving and village/market crafts, with regional attribution kept distinct where evidence permits." data-fa="مناطق کردنشین سوریه: بافت و صنایع روستایی و بازاری؛ در موارد ممکن، تفاوت‌های منطقه‌ای جداگانه ثبت می‌شود." data-tr="Suriye'deki Kürt yerleşimlerinde dokuma ve köy/pazar zanaatları; kanıtın izin verdiği yerde bölgesel ayrım korunur." data-ar="المناطق ذات الوجود الكردي في سوريا: النسيج وحرف القرى والأسواق، مع الحفاظ على الفروق الإقليمية حيث تسمح الأدلة.">بافت و دەستکاریی ناوچەیی</span></div>
  </div>
</div>

<div class="craft-catalog">
<h3 data-ku="کاتەلۆگی بەرهەمە دەستییەکان" data-en="Craft product catalogue" data-fa="کاتالوگ محصولات صنایع دستی" data-tr="El sanatı ürün kataloğu" data-ar="كتالوج المنتجات الحرفية">کاتەلۆگی بەرهەمە دەستییەکان</h3>
<div class="craft-product-grid">
'''
products=[
('قاڵی و گلیم','Carpets & Kilims','قالی و گلیم','Halı ve Kilim','السجاد والكليم','https://commons.wikimedia.org/wiki/Special:Redirect/file/Senneh%20prayer%20kilim%2019thC.JPG','https://commons.wikimedia.org/wiki/File:Senneh_prayer_kilim_19thC.JPG','ڕۆژهەڵات • سنە / بیجار','Kurdish carpet and kilim traditions include both pile rugs and flatweaves. Senneh/Sanandaj is documented as a major weaving center, while Bijar is internationally known for carpet production.','قالی و گلیم کوردی هم بافت پرزدار و هم بافت تخت را دربرمی‌گیرد. سنه/سنندج مرکز مهم بافت و بیجار از مراکز شناخته‌شده قالی است.','قاڵی و گلیم تەنها یەک شێواز نین؛ جۆری پرزدار و تخت‌بافت هەیە. سنە و بیجار لە ناوەندی ناسراوی بافتن.','Halı ve kilim geleneğinde hem havlı hem düz dokuma örnekleri vardır. Senneh/Sanandaj ve Bijar önemli merkezlerdir.','تشمل تقاليد السجاد والكليم أنماطاً ذات وبر وأنماطاً مسطحة؛ وتعد سنندج وبيجار من المراكز المعروفة.'),
('جاجم و بافتە تختەکان','Jajim & Flatweaves','جاجیم و بافته‌های تخت','Jajim ve düz dokumalar','الجَجيم والمنسوجات المسطحة','https://commons.wikimedia.org/wiki/Special:Redirect/file/Sehna%20Kilim.jpg','https://commons.wikimedia.org/wiki/Category:Rugs_and_carpets_of_Sanandaj','ڕۆژهەڵات • سنە و ناوچەکانی زاگرۆس','Striped and geometric flatweaves are used as covers, household textiles and decorative pieces. Their exact names and uses vary by locality.','جاجیم و بافته‌های تخت در پوشش، زیرانداز و وسایل خانه کاربرد داشته‌اند و نام و کاربردشان در هر منطقه متفاوت است.','جاجم و بافتە تختەکان بۆ پۆشین، پەردە و کەلوپەل بەکاردێن؛ ناو و کارکرد لە ناوچەکان جیاوازە.','Çizgili ve geometrik düz dokumalar örtü, ev tekstili ve dekorasyon için kullanılır; adlandırma bölgeye göre değişir.','تستخدم المنسوجات المسطحة المخططة والهندسية للأغطية والمنسوجات المنزلية والزينة، وتختلف تسمياتها حسب المنطقة.'),
('قاڵی هۆزی و نووجەی','Tribal rugs / Nowjay','قالی‌های عشایری و نووجی','Aşiret halıları / Nowjay','السجاد العشائري / نوجاي','https://commons.wikimedia.org/wiki/Special:Redirect/file/4.%20Kurdish%20Textile%20and%20Cultural%20Museum,%20Citadel%20of%20Erbil.%20Carpet.%20Rug%20%22Nowjay%22,%20Herki%20Tribe.%20Early%201900s.jpg','https://commons.wikimedia.org/wiki/File:4._Kurdish_Textile_and_Cultural_Museum,_Citadel_of_Erbil._Carpet._Rug_%22Nowjay%22,_Herki_Tribe._Early_1900s.jpg','باشوور • هەولێر / هێرکی','The Erbil Kurdish Textile and Cultural Museum documents a rug called “Nowjay”, attributed to the Herki tribe and dated to the early 1900s.','موزه پارچه و فرهنگ کوردی اربیل نمونه‌ای با عنوان «Nowjay» را به هێرکی و اوایل قرن بیستم نسبت می‌دهد.','مۆزەخانەی تێکستایل و کەلتووری کوردیی هەولێر نموونەیەکی «نووجەی» بە هۆزی هێرکی و سەرەتای سەدەی ٢٠ پەیوەست دەکات.','Erbil Kürt Tekstil ve Kültür Müzesi, Herki aşiretine atfedilen ve 1900’lerin başına tarihlenen “Nowjay” adlı bir halıyı belgeler.','يوثق متحف النسيج والثقافة الكردية في أربيل سجادة باسم «نوجاي» منسوبة إلى عشيرة هيركي ومؤرخة إلى أوائل القرن العشرين.'),
('زیوەر و زیوی دەستی','Silver & Gold Jewellery','زیورآلات نقره و طلا','Gümüş ve altın takılar','المجوهرات الفضية والذهبية','https://commons.wikimedia.org/wiki/Special:Redirect/file/A%20group%20of%20traditional%20Kurdish%20silver%20and%20gold%20jewlery.%20The%20right%202%20rows%20are%20anklets%20and%20ankle%20bracelets,%20100%20years%20old.%20Jewish%20craftmanship.%20Kurd%27s%20Heritage%20Museum,%20Sulaymaniyah,%20Iraq.jpg','https://commons.wikimedia.org/wiki/File:A_group_of_traditional_Kurdish_silver_and_gold_jewlery._The_right_2_rows_are_anklets_and_ankle_bracelets,_100_years_old._Jewish_craftmanship._Kurd%27s_Heritage_Museum,_Sulaymaniyah,_Iraq.jpg','باشوور • سلێمانی','Jewelry includes necklaces, bracelets, anklets, buckles and head ornaments. The Sulaymaniyah Heritage Museum preserves examples made around a century ago, including work by Jewish artisans.','زیورآلات شامل گردنبند، دستبند، پابند، سگک و تزئینات سر است. موزه میراث سلیمانیه نمونه‌های حدود یک قرن پیش را حفظ کرده است.','زیوەرەکان گردن‌دەن، دەستبەند، پێبەند، پەستاند و زیوەرە سەرییەکان دەگرێتەوە؛ مۆزەخانەی سلێمانی نموونەی کۆنی پاراستووە.','Takılar kolye, bilezik, halhal, kemer tokası ve baş süslerini içerir; Süleymaniye Miras Müzesi yaklaşık bir asırlık örnekler saklar.','تشمل المجوهرات القلائد والأساور والخلاخيل وأبازيم الأحزمة وزينة الرأس؛ ويحفظ متحف تراث السليمانية أمثلة تعود إلى نحو قرن.'),
('پەستاند و بەستەری زیوی','Silver buckles & belts','سگک و کمربند نقره‌ای','Gümüş tokalar ve kemerler','أبازيم وأحزمة فضية','https://commons.wikimedia.org/wiki/Special:Redirect/file/Silver%20buckle,%20part%20of%20a%20traditional%20silver%20belt%20from%20Kurdish%20women.%20Made%20in%20Sulaymaniyah%20100%20years%20ago%20by%20Jewish%20craftsmanship.%20Kurd%27s%20Heritage%20Museum,%20Sulaymaniyah,%20Iraq.jpg','https://commons.wikimedia.org/wiki/File:Silver_buckle,_part_of_a_traditional_silver_belt_from_Kurdish_women._Made_in_Sulaymaniyah_100_years_ago_by_Jewish_craftsmanship._Kurd%27s_Heritage_Museum,_Sulaymaniyah,_Iraq.jpg','باشوور • سلێمانی','Silver belt buckles are both functional and ornamental. A documented museum example was made in Sulaymaniyah about 100 years ago.','سگک کمربند نقره‌ای هم کارکردی و هم تزئینی است؛ یک نمونه مستند موزه‌ای در سلیمانیه حدود ۱۰۰ سال پیش ساخته شده است.','پەستاندی زیوی هەردوو کارکردی و جوانکارییە؛ نموونەیەکی مۆزەخانەیی لە سلێمانی نزیکەی سەدەیەک پێش ئێستا دروست کراوە.','Gümüş kemer tokaları hem işlevsel hem süsleyicidir; müze örneklerinden biri yaklaşık 100 yıl önce Süleymaniye’de yapılmıştır.','أبازيم الأحزمة الفضية وظيفية وزخرفية معاً؛ ومن الأمثلة المتحفية ما صنع في السليمانية قبل نحو قرن.'),
('مسگری و کەلوپەلی مسی','Copperware & Coppersmithing','مسگری و ظروف مسی','Bakırcılık','النحاسيات','https://commons.wikimedia.org/wiki/Special:Redirect/file/Coppersmith%3B%20making%20of%20trays,%20pots,%20jugs,%20and%20a%20variety%20of%20household%20items.%20Kurd%27s%20Heritage%20Museum,%20Sulaymaniyah,%20Iraqi%20Kurdistan.jpg','https://commons.wikimedia.org/wiki/File:Coppersmith;_making_of_trays,_pots,_jugs,_and_a_variety_of_household_items._Kurd%27s_Heritage_Museum,_Sulaymaniyah,_Iraqi_Kurdistan.jpg','باشوور • سلێمانی و بازاڕە کۆنەکان','Coppersmithing produces trays, pots, jugs and household vessels; engraving and hammering can add geometric or floral decoration.','مسگری شامل سینی، دیگ، کوزه، پارچ و ظروف خانگی است و گاهی با چکش‌کاری و حکاکی تزئین می‌شود.','مسگری سینی، قاپ، کوزە و کەلوپەلی ماڵ دروست دەکات و زۆرجار بە چەقۆڵ و نەخش جوانکاری دەکرێت.','Bakırcılık tepsi, tencere, ibrik ve ev eşyaları üretir; dövme ve kazıma ile geometrik veya bitkisel süsleme yapılabilir.','تشمل صناعة النحاس الصواني والقدور والأباريق والأدوات المنزلية، وقد تزين بالطرق والحفر.'),
('سفال و کۆزەسازی','Pottery & Ceramics','سفال و سرامیک','Çömlekçilik ve seramik','الفخار والسيراميك','https://commons.wikimedia.org/wiki/Special:Redirect/file/Large%20pottery%20jar.%20Made%20in%20the%20territories%20of%20Ardalan%20Kingdom%20%28%20in%20modern-day%20western%20Iran%20or%20Kurdistan%20Province%20of%20Iran%29.%2019th%20century%20CE.%20Kurd%27s%20Heritage%20Museum,%20Sulaymaniyah,%20Iraq.jpg','https://commons.wikimedia.org/wiki/File:Large_pottery_jar._Made_in_the_territories_of_Ardalan_Kingdom_(in_modern-day_western_Iran_or_Kurdistan_Province_of_Iran)._19th_century_CE._Kurd%27s_Heritage_Museum,_Sulaymaniyah,_Iraq.jpg','ڕۆژهەڵات / باشوور • ئەردەڵان','Museum documentation includes a large 19th-century pottery jar associated with the territories of the Ardalan Kingdom. Pottery traditions are broader than Kurdish identity alone and should be described by locality.','مستندات موزه‌ای نمونه‌ای از کوزه بزرگ قرن نوزدهم را به قلمرو اردلان نسبت می‌دهد. سفالگری سنتی گسترده‌تر از هویت کردی است و باید بر اساس محل توصیف شود.','مۆزەخانە نموونەی کوزەیەکی گەورەی سەدەی ١٩ بە ناوچەکانی دەسەڵاتی ئەردەڵان پەیوەست دەکات؛ سفالکاری لە کۆمەڵگەکانی دیکەش هاوبەشە.','Müze kayıtlarında 19. yüzyıla ait büyük bir çömlek Ardalan topraklarıyla ilişkilendirilir. Çömlekçilik Kürt kimliğiyle sınırlı olmayan daha geniş bir bölgesel gelenektir.','توثق المتاحف إناءً فخارياً كبيراً من القرن التاسع عشر مرتبطاً بأراضي أردلان؛ وصناعة الفخار تقليد إقليمي أوسع من الهوية الكردية وحدها.'),
('کەلوپەلی سفالی و نەخشدار','Painted pottery','ظروف سفالی نقاشی‌شده','Boyalı çömlek','الفخار المزخرف','https://commons.wikimedia.org/wiki/Special:Redirect/file/2.%20Painted%20pottery,%20Jemdet%20Nasr%20period,%20c.%203000%20BCE.%20From%20Greza,%20Shahrizor%20Plain,%20Sulaymaniyah,%20Iraq.%20Sulaymaniyah%20Museum,%20Iraqi%20Kurdistan.jpg','https://commons.wikimedia.org/wiki/File:2._Painted_pottery,_Jemdet_Nasr_period,_c._3000_BCE._From_Greza,_Shahrizor_Plain,_Sulaymaniyah,_Iraq._Sulaymaniyah_Museum,_Iraqi_Kurdistan.jpg','باشوور • شاریزۆر / سلێمانی','Archaeological pottery from the Shahrizor Plain demonstrates a long history of ceramic production in the wider region; it is presented here as archaeological heritage, not as proof of a modern ethnic label.','سفال باستانی دشت شهرزور نشان‌دهنده پیشینه طولانی تولید سفال در منطقه است؛ اینجا به‌عنوان میراث باستان‌شناختی ارائه می‌شود، نه اثبات یک برچسب قومی مدرن.','سفالی کۆنی دەشتی شاریزۆر نیشانەی مێژووی درێژی بەرهەمهێنانی سفال لە ناوچەکەیە؛ بەڵگەی ناسنامەی ئەتنیکیی نوێ نییە.','Şehrizor Ovası arkeolojik seramikleri bölgenin uzun üretim geçmişini gösterir; modern etnik kimliğin kanıtı olarak sunulmaz.','تظهر فخاريات سهل شهرزور الأثرية تاريخاً طويلاً لصناعة الفخار في المنطقة، ولا تقدم دليلاً على تسمية إثنية حديثة.'),
('کڵاش','Klash / Hawrami footwear','کلاش / پای‌افزار هورامی','Klaş / Hewrami ayakkabısı','الكلاش / أحذية هورامان','https://commons.wikimedia.org/wiki/Special:Redirect/file/Kllash-Hewrami.JPG','https://commons.wikimedia.org/wiki/File:Kllash-Hewrami.JPG','ڕۆژهەڵات • هەورامان','Klash is a handmade textile footwear tradition associated especially with Hawraman and neighboring mountain communities. The cited Commons photograph is CC BY-SA 4.0.','کلاش پای‌افزاری دست‌ساز است که به‌ویژه با هورامان و جوامع کوهستانی پیرامون آن پیوند دارد. تصویر منبع دارای مجوز CC BY-SA 4.0 است.','کڵاش پێڵاوێکی دەستییە و بە تایبەتی بە هەورامان و کۆمەڵگە شاخاوییەکانی دەوروبەر پەیوەندیدارە.','Klaş, özellikle Hewraman ve çevresindeki dağ topluluklarıyla ilişkilendirilen el yapımı bir ayakkabıdır.','الكلاش حذاء يدوي يرتبط خصوصاً بهورامان والمجتمعات الجبلية المجاورة.'),
('نازک‌کاری و کاری دار','Wood carving & fine woodworking','نازک‌کاری و منبت‌کاری چوب','Ahşap oymacılığı','النحت والخشب الدقيق','https://commons.wikimedia.org/wiki/Special:Redirect/file/A%20child%20making%20crafts%20from%20woods.jpg','https://commons.wikimedia.org/wiki/File:A_child_making_crafts_from_woods.jpg','باشوور • کوردستانی عێراق','Woodworking includes carving, boxes, household objects and decorative pieces. A Commons photograph documents a Kurdish child making wood crafts in Iraqi Kurdistan.','چوب‌کاری شامل کنده‌کاری، صندوق، وسایل خانگی و قطعات تزئینی است. یک عکس دارای مجوز، ساخت صنایع چوبی توسط یک کودک کرد در کردستان عراق را ثبت کرده است.','دارکاری بریتییە لە نەخشاندن، سندوق، کەلوپەلی ماڵ و بەرهەمی جوانکاری؛ وێنەیەکی Commons کاری دارسازی لە کوردستانی عێراق پیشان دەدات.','Ahşap işleri oyma, sandık, ev eşyaları ve dekoratif parçaları kapsar. Commons’ta Irak Kürdistanı’nda ahşap işi yapan Kürt bir çocuk fotoğraflanmıştır.','تشمل صناعة الخشب النحت والصناديق والأدوات المنزلية والقطع الزخرفية؛ وتوثق صورة من Commons طفلاً كردياً يصنع مشغولات خشبية في كردستان العراق.'),
('هەڵکەندن و کاری ئاوێنە و تێکستایل','Mirrorwork & textile decoration','آینه‌کاری و تزئینات پارچه‌ای','Ayna işi ve tekstil süslemesi','تزيين المرايا والمنسوجات','https://commons.wikimedia.org/wiki/Special:Redirect/file/Mirror%20Tapestries%20-%20Kurdish%20Textile%20Museum%20-%20Erbil%20-%20Iraq.jpg','https://commons.wikimedia.org/wiki/File:Mirror_Tapestries_-_Kurdish_Textile_Museum_-_Erbil_-_Iraq.jpg','باشوور • هەولێر','The Kurdish Textile Museum in Erbil documents textile displays including mirror-related decorative work; textile ornament varies by community and period.','موزه نساجی کوردی اربیل نمونه‌هایی از تزئینات پارچه‌ای مرتبط با آینه را ثبت کرده است؛ تزئینات در میان جوامع و دوره‌ها متفاوت است.','مۆزەخانەی تێکستایلی کوردی لە هەولێر نموونەی کاری جوانکاری پارچە و ئاوێنەیی هەیە؛ شێوازەکان بە پێی کۆمەڵگە و سەردەم دەگۆڕێن.','Erbil Kürt Tekstil Müzesi tekstil ve ayna süsleme örneklerini belgeler; süsleme biçimleri topluluk ve döneme göre değişir.','يوثق متحف النسيج الكردي في أربيل أعمالاً زخرفية للنسيج والمرايا؛ وتختلف الأساليب باختلاف المجتمع والفترة.'),
('کڵاش‌بافیی هاوچەرخ','Contemporary klash weaving','کلاش‌بافی معاصر','Güncel klash dokumacılığı','نسج الكلاش المعاصر','https://commons.wikimedia.org/wiki/Special:Redirect/file/Kalash%20Weaving%20in%20Sanandaj%209%20%28Mehr,%202026%29.jpg','https://commons.wikimedia.org/wiki/File:Kalash_Weaving_in_Sanandaj_9_(Mehr,_2026).jpg','ڕۆژهەڵات • سنە','Recent documentation from Sanandaj shows men and women continuing to weave klash and adapting the product to contemporary colors and markets.','گزارش تصویری جدید از سنندج ادامه کلاش‌بافی توسط زنان و مردان و سازگاری محصول با رنگ‌ها و بازار امروز را نشان می‌دهد.','بەڵگەی نوێی سنە بەردەوامی کڵاش‌بافی لەلایەن ژن و پیاو و گۆڕینی ڕەنگ و بازاڕی بەرهەمەکە پیشان دەدات.','Sanandaj’daki güncel belgeler kadın ve erkeklerin klash örmeye devam ettiğini ve ürünü çağdaş renk ve pazarlara uyarladığını gösterir.','تظهر توثيقات حديثة من سنندج استمرار نسج الكلاش من قبل النساء والرجال وتكييف المنتج مع الألوان والأسواق المعاصرة.'),
]
for pr in products:
    ku,en,fa,tr,ar,img,src,region,desc_en,desc_fa,desc_ku,desc_tr,desc_ar=pr
    section += f'''<article class="craft-product-card"><div class="craft-image-wrap"><img loading="lazy" src="{img}" alt="{en}"><span class="craft-region-badge">{region}</span></div><div class="craft-product-body"><h4 data-ku="{ku}" data-en="{en}" data-fa="{fa}" data-tr="{tr}" data-ar="{ar}">{ku}</h4><p class="craft-desc" data-ku="{desc_ku}" data-en="{desc_en}" data-fa="{desc_fa}" data-tr="{desc_tr}" data-ar="{desc_ar}">{desc_ku}</p><a class="craft-source" href="{src}" target="_blank" rel="noopener" data-ku="سەرچاوە و مۆڵەتی وێنە" data-en="Image source &amp; license" data-fa="منبع و مجوز تصویر" data-tr="Görsel kaynağı ve lisans" data-ar="مصدر الصورة والترخيص">سەرچاوە و مۆڵەتی وێنە ↗</a></div></article>'''
section += r'''</div></div>

<div class="craft-detail-grid">
  <div class="craft-detail-card"><h3 data-ku="بەرهەمەکانی نەسجی" data-en="Textile products" data-fa="محصولات نساجی" data-tr="Tekstil ürünleri" data-ar="منتجات النسيج">بەرهەمەکانی نەسجی</h3><ul><li>قاڵی / قالی پرزدار</li><li>گلیم و سۆفڕە</li><li>جاجم</li><li>مفڕەش و چووال</li><li>پۆشاک و پارچەی دەستی</li><li>سوزن‌کاری، نەخش و هەڵکەندن</li></ul></div>
  <div class="craft-detail-card"><h3 data-ku="بەرهەمەکانی فلزکاری" data-en="Metalwork products" data-fa="محصولات فلزکاری" data-tr="Metal işçiliği ürünleri" data-ar="منتجات المشغولات المعدنية">بەرهەمەکانی فلزکاری</h3><ul><li>سینی و قاپی مسی</li><li>کوزە و ئیبریق</li><li>پەستاند و بەستەر</li><li>زیوەر و پێوەکراوەکان</li><li>کەلوپەلی ماڵی</li><li>نەخش و حکاکیی فلز</li></ul></div>
  <div class="craft-detail-card"><h3 data-ku="بەرهەمەکانی دار و چەرم" data-en="Wood &amp; leather products" data-fa="محصولات چوب و چرم" data-tr="Ahşap ve deri ürünleri" data-ar="منتجات الخشب والجلد">بەرهەمەکانی دار و چەرم</h3><ul><li>سندوق و جەعبە</li><li>میز و کەلوپەلی ماڵ</li><li>شطرەنج و کارە دەستییە جوانکارییەکان</li><li>کەلوپەلی چەرم</li><li>بەستەر و کیسە</li><li>پێڵاو و بەرهەمە ناوخۆییەکان</li></ul></div>
  <div class="craft-detail-card"><h3 data-ku="بەرهەمەکانی خاک و پشم" data-en="Clay &amp; wool products" data-fa="محصولات سفالی و پشمی" data-tr="Kil ve yün ürünleri" data-ar="منتجات الطين والصوف">بەرهەمەکانی خاک و پشم</h3><ul><li>کوزە و قاپی سفالی</li><li>کەلوپەلی نەخشدار</li><li>نمد</li><li>پۆششی پشمی</li><li>کەلوپەلی ماڵی</li><li>بەرهەمە ناوچەییەکان</li></ul></div>
</div>

<div class="craft-academic-note"><h3 data-ku="تێبینی زانستی و مێژوویی" data-en="Academic &amp; historical note" data-fa="یادداشت علمی و تاریخی" data-tr="Akademik ve tarihî not" data-ar="ملاحظة أكاديمية وتاريخية">تێبینی زانستی و مێژوویی</h3><p data-ku="دەستکارییەکانی کوردستان لە ژینگەیەکی گەورەی کەلتووریی زاگرۆس و میزۆپۆتامیا و ئەناتۆڵیا و ڕۆژهەڵاتی نزیکدا پەرەیان سەندووە. بۆیە هەندێک تکنیک و بەرهەم هاوبەشن و نابێت بە ناوی یەک نەتەوەیەوە سنووردار بکرێن. لەم کاتەلۆگەدا ناوی ناوچە، مادە، تکنیک و سەرچاوە جیا کراونەتەوە بۆ ئەوەی زانیارییەکە بە شێوەیەکی بەڵگەدار و زانستی بخوێندرێتەوە." data-en="Kurdish craft traditions developed within a wider cultural zone spanning the Zagros, Mesopotamia, Anatolia and the Near East. Many techniques and products are shared across communities; they should not be assigned exclusively to one ethnicity without evidence. This catalogue therefore separates locality, material, technique and source so the information can be read critically." data-fa="صنایع دستی کردستان در پهنه فرهنگی گسترده زاگرس، میان‌رودان، آناتولی و خاور نزدیک شکل گرفته‌اند. بسیاری از فنون و محصولات میان جوامع مشترک‌اند و بدون مدرک نباید به‌طور انحصاری به یک قوم نسبت داده شوند. در این کاتالوگ محل، ماده، تکنیک و منبع از هم تفکیک شده‌اند." data-tr="Kürt zanaat gelenekleri Zagros, Mezopotamya, Anadolu ve Yakın Doğu'yu kapsayan daha geniş bir kültürel ortamda gelişmiştir. Birçok teknik ve ürün topluluklar arasında ortaktır; kanıt olmadan tek bir etnisiteye özel atfedilmemelidir. Bu katalog yer, malzeme, teknik ve kaynağı ayrı gösterir." data-ar="تطورت الحرف الكردية ضمن نطاق ثقافي أوسع يشمل زاغروس وبلاد الرافدين والأناضول والشرق الأدنى. وتشترك مجتمعات متعددة في كثير من التقنيات والمنتجات، لذلك لا ينبغي نسبتها حصراً إلى إثنية واحدة دون دليل. ويفصل هذا الكتالوج بين المكان والمادة والتقنية والمصدر.">دەستکارییەکان لە کۆمەڵگە و ناوچە جیاوازەکاندا پەرەیان سەندووە؛ بۆیە جیاوازی نێوان «کوردی»، «ناوچەیی» و «هاوبەش» بە هەستی زانستی پارێزراوە.</p></div>

<div class="craft-sources"><h3 data-ku="سەرچاوە سەرەکییەکان" data-en="Core research sources" data-fa="منابع پژوهشی اصلی" data-tr="Temel araştırma kaynakları" data-ar="المصادر البحثية الأساسية">سەرچاوە سەرەکییەکان</h3><div class="source-chip-row"><a href="https://www.iranicaonline.org/articles/carpets-xiv/" target="_blank" rel="noopener">Encyclopaedia Iranica — Tribal Carpets</a><a href="https://www.iranicaonline.org/articles/bijar-a-town-and-a-sahrestan-county-in-the-kurdistan-province-of-iran/" target="_blank" rel="noopener">Encyclopaedia Iranica — Bijar</a><a href="https://heritage.krd/art-and-craft" target="_blank" rel="noopener">Heritage.KRD — Art &amp; Craft</a><a href="https://commons.wikimedia.org/wiki/Category:Kurd%27s_Heritage_Museum_(Sulaymaniyah)" target="_blank" rel="noopener">Wikimedia Commons — Kurd's Heritage Museum</a></div></div>
</section>
'''
s=s[:start]+section+s[end:]
# Update card description for 09
import re
pat=r'(<button[^>]*data-target="handicrafts"[^>]*>.*?<span class="card-desc")[^>]*(></span>)'
m=re.search(pat,s,re.S)
if m:
    repl=m.group(1)+r' data-ar="السجاد والكليم والمجوهرات والنحاس والخشب والفخار والكلاش والمنسوجات، مع صور ومصادر لكل مجموعة." data-en="A visual craft archive covering carpets, kilims, jewelry, copper, wood, pottery, klash and textiles with regional context and image sources." data-fa="آرشیو تصویری صنایع دستی شامل قالی، گلیم، زیور، مس، چوب، سفال، کلاش و منسوجات با زمینه منطقه‌ای و منابع تصاویر." data-ku="کاتەلۆگێکی وێنەیی بۆ قاڵی، گلیم، زیوەر، مسگری، دارکاری، سفال، کڵاش و نەسج لەگەڵ سەرچاوەی وێنە و زانیاریی ناوچەیی." data-tr="Halı, kilim, takı, bakır, ahşap, çömlek, klash ve tekstilleri bölgesel bağlam ve görsel kaynaklarıyla sunan görsel arşiv."'+m.group(2)
    s=s[:m.start()]+repl+s[m.end():]
p.write_text(s,encoding='utf-8')

css=Path('/mnt/data/work9/styles.css')
c=css.read_text(encoding='utf-8')
c += r'''

/* Card 09 — Kurdish handicrafts visual archive */
.craft-section{overflow:hidden}
.craft-hero-box{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px;align-items:center;margin:18px 0;padding:24px;border:1px solid rgba(212,175,55,.38);border-radius:22px;background:linear-gradient(135deg,rgba(15,15,15,.98),rgba(34,27,13,.94));box-shadow:0 16px 45px rgba(0,0,0,.28)}
.craft-kicker{display:inline-block;font-size:.72rem;letter-spacing:.12em;color:#d7b45b;font-weight:800;margin-bottom:8px}
.craft-hero-box h3{margin:0 0 10px;font-size:1.65rem}.craft-hero-box p{margin:0;line-height:1.95;color:var(--muted,#bcbcbc)}
.craft-stat-row{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;min-width:250px}.craft-stat-row span{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:90px;padding:12px;border:1px solid rgba(212,175,55,.28);border-radius:16px;background:rgba(0,0,0,.26)}.craft-stat-row b{font-size:1.45rem;color:#e4bd64}.craft-stat-row small{text-align:center;color:#aaa;line-height:1.4}
.craft-method-box,.craft-region-summary,.craft-academic-note,.craft-sources{margin:18px 0;padding:20px;border-radius:20px;border:1px solid rgba(212,175,55,.2);background:rgba(255,255,255,.025)}
.craft-method-box h3,.craft-region-summary h3,.craft-catalog>h3,.craft-academic-note h3,.craft-sources h3{margin-top:0}.craft-method-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.craft-method-grid>div{display:flex;gap:10px;align-items:flex-start;padding:14px;border-radius:14px;background:rgba(255,255,255,.035)}.craft-method-grid b{color:#e2b95f}.craft-method-grid span{line-height:1.75;color:#c6c6c6}
.craft-region-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.craft-region{padding:16px;border-radius:16px;background:linear-gradient(180deg,rgba(212,175,55,.08),rgba(255,255,255,.02));border:1px solid rgba(212,175,55,.18)}.craft-region strong{display:block;color:#e1ba60;margin-bottom:7px;font-size:1.05rem}.craft-region span{color:#c8c8c8;line-height:1.75;font-size:.92rem}
.craft-product-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.craft-product-card{overflow:hidden;border:1px solid rgba(212,175,55,.2);border-radius:18px;background:rgba(255,255,255,.025);box-shadow:0 10px 30px rgba(0,0,0,.18);transition:transform .2s ease,box-shadow .2s ease,border-color .2s ease}.craft-product-card:hover{transform:translateY(-4px);border-color:rgba(212,175,55,.55);box-shadow:0 16px 38px rgba(0,0,0,.28)}.craft-image-wrap{position:relative;aspect-ratio:16/10;background:#111;overflow:hidden}.craft-image-wrap img{width:100%;height:100%;object-fit:cover;display:block}.craft-region-badge{position:absolute;bottom:10px;right:10px;padding:5px 9px;border-radius:999px;background:rgba(0,0,0,.76);border:1px solid rgba(212,175,55,.4);color:#f0cc73;font-size:.75rem}.craft-product-body{padding:16px}.craft-product-body h4{margin:0 0 8px;color:#e3bd65;font-size:1.05rem}.craft-desc{margin:0 0 13px;line-height:1.8;color:#c6c6c6;font-size:.9rem}.craft-source{display:inline-flex;align-items:center;gap:5px;color:#e4c477;text-decoration:none;font-size:.82rem}.craft-source:hover{text-decoration:underline}.craft-detail-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:20px}.craft-detail-card{padding:18px;border-radius:16px;border:1px solid rgba(212,175,55,.16);background:rgba(255,255,255,.025)}.craft-detail-card h3{font-size:1rem;color:#dfba61}.craft-detail-card ul{padding-inline-start:20px;margin:0}.craft-detail-card li{margin:7px 0;color:#c7c7c7}.craft-academic-note p{line-height:1.95;color:#c6c6c6}.source-chip-row{display:flex;flex-wrap:wrap;gap:9px}.source-chip-row a{padding:8px 12px;border-radius:999px;border:1px solid rgba(212,175,55,.25);color:#e2bd68;text-decoration:none;font-size:.8rem;background:rgba(212,175,55,.05)}.source-chip-row a:hover{background:rgba(212,175,55,.12)}
@media(max-width:1000px){.craft-product-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.craft-region-grid,.craft-detail-grid{grid-template-columns:repeat(2,1fr)}.craft-method-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:700px){.craft-hero-box{grid-template-columns:1fr}.craft-stat-row{grid-template-columns:repeat(3,1fr);min-width:0}.craft-product-grid,.craft-region-grid,.craft-detail-grid,.craft-method-grid{grid-template-columns:1fr}.craft-hero-box{padding:18px}.craft-stat-row small{font-size:.72rem}}
'''
css.write_text(c,encoding='utf-8')

# Sources documentation
src=Path('/mnt/data/work9/HANDICRAFTS-SOURCES.md')
src.write_text('''# Card 09 — Kurdish Handicrafts: research and image sources\n\n## Research sources\n- Encyclopaedia Iranica, CARPETS xiv. Tribal Carpets — https://www.iranicaonline.org/articles/carpets-xiv/\n- Encyclopaedia Iranica, BĪJĀR — https://www.iranicaonline.org/articles/bijar-a-town-and-a-sahrestan-county-in-the-kurdistan-province-of-iran/\n- Encyclopaedia Iranica, Kermanshah geography (crafts include kilim, carpet, cotton-shoe, woodwork and metalwork) — https://www.iranicaonline.org/articles/kermanshah-01-geography/\n- Heritage.KRD, Art & Craft — https://heritage.krd/art-and-craft\n\n## Image sources and licenses\nAll image URLs in the card use Wikimedia Commons Special:Redirect/file links so the site loads the source image directly. Each product card links to its source page. Licenses vary by image; the source page is authoritative for the current license and attribution.\n\n- Senneh prayer kilim — https://commons.wikimedia.org/wiki/File:Senneh_prayer_kilim_19thC.JPG\n- Sehna Kilim / Sanandaj rugs category — https://commons.wikimedia.org/wiki/Category:Rugs_and_carpets_of_Sanandaj\n- Nowjay / Herki rug — https://commons.wikimedia.org/wiki/File:4._Kurdish_Textile_and_Cultural_Museum,_Citadel_of_Erbil._Carpet._Rug_%22Nowjay%22,_Herki_Tribe._Early_1900s.jpg\n- Traditional silver and gold jewellery — https://commons.wikimedia.org/wiki/File:A_group_of_traditional_Kurdish_silver_and_gold_jewlery._The_right_2_rows_are_anklets_and_ankle_bracelets,_100_years_old._Jewish_craftmanship._Kurd%27s_Heritage_Museum,_Sulaymaniyah,_Iraq.jpg\n- Silver buckle — https://commons.wikimedia.org/wiki/File:Silver_buckle,_part_of_a_traditional_silver_belt_from_Kurdish_women._Made_in_Sulaymaniyah_100_years_ago_by_Jewish_craftsmanship._Kurd%27s_Heritage_Museum,_Sulaymaniyah,_Iraq.jpg\n- Coppersmith — https://commons.wikimedia.org/wiki/File:Coppersmith;_making_of_trays,_pots,_jugs,_and_a_variety_of_household_items._Kurd%27s_Heritage_Museum,_Sulaymaniyah,_Iraqi_Kurdistan.jpg\n- Ardalan pottery jar — https://commons.wikimedia.org/wiki/File:Large_pottery_jar._Made_in_the_territories_of_Ardalan_Kingdom_(in_modern-day_western_Iran_or_Kurdistan_Province_of_Iran)._19th_century_CE._Kurd%27s_Heritage_Museum,_Sulaymaniyah,_Iraq.jpg\n- Shahrizor painted pottery — https://commons.wikimedia.org/wiki/File:2._Painted_pottery,_Jemdet_Nasr_period,_c._3000_BCE._From_Greza,_Shahrizor_Plain,_Sulaymaniyah,_Iraq._Sulaymaniyah_Museum,_Iraqi_Kurdistan.jpg\n- Kllash-Hewrami — https://commons.wikimedia.org/wiki/File:Kllash-Hewrami.JPG\n- Wood craft — https://commons.wikimedia.org/wiki/File:A_child_making_crafts_from_woods.jpg\n- Mirror tapestries — https://commons.wikimedia.org/wiki/File:Mirror_Tapestries_-_Kurdish_Textile_Museum_-_Erbil_-_Iraq.jpg\n- Contemporary klash weaving, Sanandaj — https://commons.wikimedia.org/wiki/File:Kalash_Weaving_in_Sanandaj_9_(Mehr,_2026).jpg\n''',encoding='utf-8')

# ensure syntax-ish static checks
print('section chars', len(section), 'products', len(products))
