from pathlib import Path
p=Path('/mnt/data/qcwork/index.html')
s=p.read_text(encoding='utf-8')
start=s.index('<section class="section" data-cultural-section="culture"')
end=s.index('</section>', start)+len('</section>')
new='''<section class="section culture-intangible-section" data-cultural-section="culture" data-master-section="true" id="culture">
<h2 data-ar="التراث غير المادي ونمط الحياة الكردي" data-en="Kurdish Intangible Heritage &amp; Ways of Life" data-fa="میراث ناملموس و شیوه‌های زندگی کردی" data-ku="میراثی نەماوی و شێوازی ژیانی کوردی" data-tr="Kürt Somut Olmayan Mirası ve Yaşam Biçimleri">میراثی نەماوی و شێوازی ژیانی کوردی</h2>
<div class="culture-intro-pro">
<div class="culture-intro-copy">
<span class="research-badge">KURDESTAN • CULTURAL ARCHIVE • 14</span>
<h3 data-ar="فرهنگ فراتر از اشیاء: سنت، حافظه و زندگی روزمره" data-en="Beyond objects: tradition, memory and everyday life" data-fa="فراتر از اشیاء؛ سنت، حافظه و زندگی روزمره" data-ku="لە پاش شتەکان: نەریت، یادەوەری و ژیانی ڕۆژانە" data-tr="Nesnelerin ötesinde: gelenek, hafıza ve gündelik yaşam">لە پاش شتەکان: نەریت، یادەوەری و ژیانی ڕۆژانە</h3>
<p data-ar="يركز هذا القسم على التراث غير المادي وأنماط الحياة التي لا تُكرر الأقسام المتخصصة في التاريخ واللغة والموسيقى والطعام والملابس والحرف. ويتناول الممارسات التي تنتقل بين الأجيال، والذاكرة الشفوية، والاحتفالات، والضيافة، والعلاقات الاجتماعية، والمعرفة المحلية." data-en="This section focuses on intangible heritage and ways of life without repeating the dedicated history, language, music, food, clothing and craft sections. It documents practices transmitted across generations, oral memory, celebrations, hospitality, social relationships and local knowledge." data-fa="این بخش بر میراث ناملموس و شیوه‌های زندگی تمرکز دارد و بخش‌های مستقل تاریخ، زبان، موسیقی، غذا، پوشاک و صنایع‌دستی را تکرار نمی‌کند. موضوع آن سنت‌های منتقل‌شده میان نسل‌ها، حافظه شفاهی، آیین‌ها، مهمان‌نوازی، روابط اجتماعی و دانش محلی است." data-ku="ئەم بەشە تەنها لەسەر میراثی نەماوی و شێوازی ژیان دەوەستێت و مێژوو، زمان، مۆسیقا، خواردن، جل و بەرگ و دەستکارییە تایبەتەکان دووبارە ناکاتەوە. بابەتەکانی گواستنەوەی نەریت لە نێوان نەوەکان، بیرەوەریی زارەکی، بۆنەکان، میوانداری، پەیوەندییە کۆمەڵایەتییەکان و زانیاریی ناوخۆیین." data-tr="Bu bölüm tarih, dil, müzik, yemek, giyim ve el sanatları için ayrılmış bölümleri tekrarlamadan somut olmayan mirasa ve yaşam biçimlerine odaklanır. Nesiller arasında aktarılan uygulamalar, sözlü hafıza, kutlamalar, misafirperverlik, toplumsal ilişkiler ve yerel bilgi ele alınır.">ئەم بەشە تەنها لەسەر میراثی نەماوی و شێوازی ژیان دەوەستێت و بابەتە تایبەتەکانی دیکە دووبارە ناکاتەوە.</p>
</div>
<div class="culture-principles">
<div><strong>١</strong><b data-ar="الذاكرة الشفوية" data-en="Oral memory" data-fa="حافظه شفاهی" data-ku="بیرەوەریی زارەکی" data-tr="Sözlü hafıza">بیرەوەریی زارەکی</b><p data-ar="حكايات العائلة والقرية والأمثال والألغاز وأشكال السرد التي تحفظ الخبرة الاجتماعية." data-en="Family and village stories, proverbs, riddles and forms of storytelling that preserve social experience." data-fa="داستان‌های خانوادگی و روستایی، ضرب‌المثل‌ها، چیستان‌ها و روایت‌هایی که تجربه اجتماعی را حفظ می‌کنند." data-ku="چیرۆکی خێزان و گوند، پەند و وتە و مەتەڵ و شێوازەکانی چیرۆکگێڕان کە ئەزموونی کۆمەڵایەتی دەپارێزن." data-tr="Aile ve köy hikâyeleri, atasözleri, bilmeceler ve toplumsal deneyimi koruyan anlatı biçimleri.">چیرۆک و پەند و مەتەڵ و ڕوایەتە زارەکییەکان.</p></div>
<div><strong>٢</strong><b data-ar="الاحتفالات والمناسبات" data-en="Celebrations &amp; life-cycle events" data-fa="جشن‌ها و آیین‌های چرخه زندگی" data-ku="بۆنە و ڕێوڕەسمەکانی ژیان" data-tr="Kutlamalar ve yaşam döngüsü törenleri">بۆنە و ڕێوڕەسمەکانی ژیان</b><p data-ar="النوروز والأعراس والختان والضيافة ومناسبات المجتمع، مع احترام الاختلافات المحلية والدينية والتاريخية." data-en="Newroz, weddings, circumcision ceremonies, hospitality and community occasions, while recognizing local, religious and historical variation." data-fa="نوروز، عروسی، آیین‌های چرخه زندگی، مهمان‌نوازی و مناسبت‌های اجتماعی، با توجه به تفاوت‌های محلی، دینی و تاریخی." data-ku="نەورۆز، زەماوەند، ڕێوڕەسمەکانی ژیان، میوانداری و بۆنە کۆمەڵایەتییەکان، بە ڕەچاوکردنی جیاوازیی ناوخۆیی و مێژوویی." data-tr="Newroz, düğünler, yaşam döngüsü törenleri, misafirperverlik ve toplumsal etkinlikler; yerel, dinî ve tarihî farklılıklar gözetilir.">نەورۆز و زەماوەند و بۆنە کۆمەڵایەتییەکان.</p></div>
<div><strong>٣</strong><b data-ar="الضيافة والتكافل" data-en="Hospitality &amp; solidarity" data-fa="مهمان‌نوازی و همیاری" data-ku="میوانداری و هاوکاری" data-tr="Misafirperverlik ve dayanışma">میوانداری و هاوکاری</b><p data-ar="ممارسات استقبال الضيف والعمل الجماعي والمساعدة المتبادلة، مع اختلاف أشكالها بين المدن والقرى والمجتمعات." data-en="Practices of welcoming guests, collective work and mutual aid, which vary across cities, villages and communities." data-fa="شیوه‌های پذیرایی از مهمان، کار جمعی و کمک متقابل که میان شهرها، روستاها و جوامع متفاوت است." data-ku="ڕێگاکانی پێشوازی لە میوان، کاری کۆمەڵایەتی و هاوکاریی دوولایەنە کە لە شار و گوند و کۆمەڵگاکاندا جیاوازن." data-tr="Misafir karşılama, kolektif çalışma ve karşılıklı yardımlaşma uygulamaları şehir, köy ve topluluklara göre değişir.">میوانداری، کاری کۆمەڵ و هاوکاریی دوولایەنە.</p></div>
<div><strong>٤</strong><b data-ar="الألعاب والرقصات الجماعية" data-en="Games &amp; communal dances" data-fa="بازی‌ها و رقص‌های جمعی" data-ku="یاری و هەڵپەڕکێی کۆمەڵایەتی" data-tr="Oyunlar ve toplu danslar">یاری و هەڵپەڕکێی کۆمەڵایەتی</b><p data-ar="أشكال اللعب والحركة الجماعية المرتبطة بالأعراس والأعياد والمناسبات، مع اختلاف الأسماء والأداء حسب المنطقة." data-en="Games and communal movement associated with weddings, festivals and gatherings, with names and performance varying by region." data-fa="بازی‌ها و حرکات جمعی مرتبط با عروسی، جشن‌ها و گردهمایی‌ها که نام و شیوه اجرا در مناطق مختلف متفاوت است." data-ku="یاری و جوڵەی کۆمەڵایەتی لە زەماوەند و جەژن و کۆبوونەوەکاندا، بە جیاوازیی ناو و شێوازی جێبەجێکردن لە ناوچەکان." data-tr="Düğün, bayram ve toplantılarla ilişkili oyunlar ve toplu hareketler; adlar ve icra bölgeye göre değişir.">یاری و هەڵپەڕکێ و بۆنە کۆمەڵایەتییەکان.</p></div>
<div><strong>٥</strong><b data-ar="المعرفة المحلية والطبيعة" data-en="Local knowledge &amp; environment" data-fa="دانش بومی و محیط زیست" data-ku="زانیاریی ناوخۆیی و سروشت" data-tr="Yerel bilgi ve çevre">زانیاریی ناوخۆیی و سروشت</b><p data-ar="معارف الزراعة والرعي والماء والجبال والنباتات والمواسم كما تحفظها المجتمعات المحلية، من دون ادعاء أن ممارسة واحدة مشتركة بين جميع الكرد." data-en="Local knowledge of farming, herding, water, mountains, plants and seasons, without implying that one practice is shared by all Kurdish communities." data-fa="دانش محلی درباره کشاورزی، دامداری، آب، کوهستان، گیاهان و فصل‌ها، بدون اینکه یک رسم واحد به همه جوامع کرد تعمیم داده شود." data-ku="زانیاریی کشتوکاڵ، ئاژەڵداری، ئاو، شاخ، ڕووەک و وەرزەکان کە کۆمەڵگا ناوخۆییەکان دەپارێزن؛ بەبێ گشتی‌کردنی بۆ هەموو کوردان." data-tr="Tarım, hayvancılık, su, dağlar, bitkiler ve mevsimlere ilişkin yerel bilgi; tek bir uygulama tüm Kürt topluluklarına genellenmez.">زانیاریی کشتوکاڵ، ئاژەڵداری و سروشت.</p></div>
<div><strong>٦</strong><b data-ar="حفظ التراث وتحوّله" data-en="Continuity &amp; change" data-fa="تداوم و دگرگونی" data-ku="بەردەوامی و گۆڕان" data-tr="Süreklilik ve değişim">بەردەوامی و گۆڕان</b><p data-ar="التراث ليس ثابتاً؛ تنتقل الممارسات وتتكيف مع التحضر والهجرة والتعليم والتكنولوجيا والشتات." data-en="Heritage is not static; practices are transmitted and adapted through urbanization, migration, education, technology and diaspora life." data-fa="میراث ثابت نیست؛ سنت‌ها با شهرنشینی، مهاجرت، آموزش، فناوری و زندگی در دیاسپورا منتقل و دگرگون می‌شوند." data-ku="میراث شتێکی جێگیر نییە؛ نەریتەکان لەگەڵ شارستانیبوون، کۆچ، فێرکردن، تەکنەلۆجیا و ژیانی دیاسپۆرا دەگوازنەوە و دەگۆڕدرێن." data-tr="Miras durağan değildir; uygulamalar kentleşme, göç, eğitim, teknoloji ve diaspora yaşamıyla aktarılır ve dönüşür.">میراث بەردەوامە، بەڵام هەموو کاتێک دەگۆڕێت.</p></div>
</div>
</div>
<div class="culture-boundaries">
<h3 data-ar="حدود هذا القسم" data-en="Editorial boundary" data-fa="مرز محتوایی این بخش" data-ku="سنووری ناوەڕۆکی ئەم بەشە" data-tr="Editoryal sınır">سنووری ناوەڕۆکی ئەم بەشە</h3>
<p data-ar="التاريخ التفصيلي موجود في بطاقة التاريخ؛ اللغة والأطلس في بطاقة اللغة؛ الموسيقى في بطاقة الموسيقى؛ الطعام في بطاقة المطبخ؛ الملابس في بطاقة الملابس؛ والحرف في بطاقة الحرف. هنا نركز فقط على التراث غير المادي، الممارسات الاجتماعية والمعرفة المحلية." data-en="Detailed history is in the History card; language and atlas in the Language card; music in Music; food in Cuisine; clothing in Clothing; and crafts in Handicrafts. This card focuses only on intangible heritage, social practices and local knowledge." data-fa="تاریخ تفصیلی در کارت تاریخ است؛ زبان و اطلس در کارت زبان؛ موسیقی در کارت موسیقی؛ غذا در کارت آشپزی؛ پوشاک در کارت لباس؛ و صنایع‌دستی در کارت صنایع‌دستی. این کارت فقط بر میراث ناملموس، رفتارهای اجتماعی و دانش محلی تمرکز دارد." data-ku="مێژووی ورد لە کارتی مێژووە؛ زمان و ئەتڵەس لە کارتی زمانە؛ مۆسیقا لە کارتی مۆسیقا؛ خواردن لە کارتی خواردن؛ جل و بەرگ لە کارتی جل؛ و دەستکاری لە کارتی دەستکارییە. ئەم کارتە تەنها لەسەر میراثی نەماوی، کردارە کۆمەڵایەتییەکان و زانیاریی ناوخۆییە." data-tr="Ayrıntılı tarih Tarih kartında; dil ve atlas Dil kartında; müzik Müzik'te; yemek Mutfak'ta; giyim Giyim'de; el sanatları El Sanatları'nda bulunur. Bu kart yalnızca somut olmayan mirasa, toplumsal uygulamalara ve yerel bilgiye odaklanır.">ئەم کارتە دووبارەکردنەوەی کارتە تایبەتەکانی دیکە نییە؛ تەنها میراثی نەماوی و شێوازی ژیان دەخاتەڕوو.</p>
</div>
<div class="culture-sources"><h3 data-ar="منهجية ومراجع" data-en="Method &amp; references" data-fa="روش و منابع" data-ku="ڕێباز و سەرچاوەکان" data-tr="Yöntem ve kaynaklar">ڕێباز و سەرچاوەکان</h3><p data-ar="التوثيق يميّز بين الممارسة الموثقة، والوصف المحلي، والتعميم غير المدعوم. تُراعى الفروق بين المناطق والفترات والجماعات، ولا تُنسب ممارسة مشتركة إلى جميع الكرد بلا دليل." data-en="Documentation distinguishes sourced practice, local description and unsupported generalization. Regional, temporal and community differences are preserved; a shared practice is not attributed to all Kurds without evidence." data-fa="در مستندسازی میان سنت مستند، توصیف محلی و تعمیم بدون پشتوانه تفاوت گذاشته می‌شود. تفاوت منطقه‌ای، زمانی و اجتماعی حفظ می‌شود و یک رسم مشترک بدون مدرک به همه کردها نسبت داده نمی‌شود." data-ku="لە بەڵگەنامەکردندا جیاوازی لە نێوان نەریتی سەرچاوەدار، وەسفی ناوخۆیی و گشتی‌کردنی بێ بەڵگە دەکرێت. جیاوازیی ناوچە، سەردەم و کۆمەڵگا پارێزراوە و نەریتێکی هاوبەش بەبێ بەڵگە بە هەموو کوردان نادرێت." data-tr="Belgeleme; kaynaklı uygulama, yerel anlatım ve desteklenmeyen genellemeyi ayırır. Bölgesel, dönemsel ve topluluk farklılıkları korunur; ortak bir uygulama kanıt olmadan tüm Kürtlere atfedilmez.">بەڵگە و سەرچاوەکان لەگەڵ جیاوازیی ناوچە و سەردەم پارێزراون.</p><div class="source-chip-row"><a href="https://ich.unesco.org/" rel="noopener" target="_blank">UNESCO Intangible Cultural Heritage</a><a href="https://www.iranicaonline.org/" rel="noopener" target="_blank">Encyclopaedia Iranica</a><a href="https://www.cambridge.org/core/books/cambridge-history-of-the-kurds/" rel="noopener" target="_blank">Cambridge — The Cambridge History of the Kurds</a></div></div>
</section>'''
s=s[:start]+new+s[end:]
# Update card 14 description to avoid repeating specialized cards.
old='data-ku="میراث، نەریت، هونەر، موسیقا، خواردن و شێوازی ژیانی کوردی."'
newattr='data-ku="میراثی نەماوی، نەریتە کۆمەڵایەتییەکان، میوانداری، بۆنەکان، بیرەوەریی زارەکی و زانیاریی ناوخۆیی؛ بەبێ دووبارەکردنەوەی کارتە تایبەتەکان."'
s=s.replace(old,newattr)
s=s.replace('data-en="Kurdish heritage, traditions, arts, music, food and ways of life."','data-en="Intangible heritage, social practices, hospitality, celebrations, oral memory and local knowledge — without repeating the dedicated cards."')
s=s.replace('data-fa="میراث، سنت‌ها، هنر، موسیقی، غذا و شیوه‌های زندگی کردی."','data-fa="میراث ناملموس، سنت‌های اجتماعی، مهمان‌نوازی، آیین‌ها، حافظه شفاهی و دانش محلی؛ بدون تکرار کارت‌های تخصصی."')
s=s.replace('data-tr="Kürt mirası, gelenekleri, sanatı, müziği, mutfağı ve yaşam biçimi."','data-tr="Somut olmayan miras, toplumsal uygulamalar, misafirperverlik, kutlamalar, sözlü hafıza ve yerel bilgi; özel kartlar tekrarlanmaz."')
s=s.replace('data-ar="التراث والتقاليد والفنون والموسيقى والطعام وأنماط الحياة الكردية."','data-ar="التراث غير المادي والممارسات الاجتماعية والضيافة والاحتفالات والذاكرة الشفوية والمعرفة المحلية دون تكرار الأقسام المتخصصة."')
p.write_text(s,encoding='utf8')

# update script culture descriptor
p=Path('/mnt/data/qcwork/script.js'); s=p.read_text(encoding='utf8')
s=s.replace("culture:{ku:'میراثی مێژوویی و کەلتووری ناوچەکە لەگەڵ شار، زمان، هونەر و نەریتەکانیدا ناسێنراوە.',fa:'میراث تاریخی و فرهنگی این بخش همراه با شهرها، زبان، هنر و سنت‌ها معرفی می‌شود.',en:'The region’s historical and cultural heritage is presented together with its cities, language, arts and traditions.',tr:'Bölgenin tarihî ve kültürel mirası şehirleri, dili, sanatı ve gelenekleriyle birlikte tanıtılır.',ar:'يُعرض التراث التاريخي والثقافي للمنطقة مع مدنها ولغتها وفنونها وتقاليدها.'}", "culture:{ku:'میراثی نەماوی، نەریتە کۆمەڵایەتییەکان، میوانداری، بۆنەکان، بیرەوەریی زارەکی و زانیاریی ناوخۆیی؛ بەبێ دووبارەکردنەوەی کارتە تایبەتەکان.',fa:'میراث ناملموس، سنت‌های اجتماعی، مهمان‌نوازی، آیین‌ها، حافظه شفاهی و دانش محلی؛ بدون تکرار کارت‌های تخصصی.',en:'Intangible heritage, social practices, hospitality, celebrations, oral memory and local knowledge — without repeating the dedicated cards.',tr:'Somut olmayan miras, toplumsal uygulamalar, misafirperverlik, kutlamalar, sözlü hafıza ve yerel bilgi; özel kartlar tekrarlanmaz.',ar:'التراث غير المادي والممارسات الاجتماعية والضيافة والاحتفالات والذاكرة الشفوية والمعرفة المحلية دون تكرار الأقسام المتخصصة.'}")
p.write_text(s,encoding='utf8')
